### ISSUE TITLE
Refactor Viewer into a Phosphor Application

### ISSUE THREAD

**Issue by quigleyj-mavenomics** [Mavenomics/MavenWorks#21]
Now that we've split off common Jupyter dependencies into a separate package, we can begin migrating the Viewer into a Phosphor application, using `JupyterFrontEnd`. The Viewer is in desperate need of de-spaghettification, it's very hard to work with and improve on in it's current state but remains important to our Jupyter story.

Copying some internal notes we took on this a while back:

## Goals

 - Reduce maintenance drag
   - Enhance code re-use between Sink, Viewer, and Lab
   - Remove existing hacks in Commands
   - Reduce code overall
 - Reduce plugin/extension drag 
   - Eliminate need for customized hacks for each MIME type renderer (and similar?) plugin
   - Allow second- and third-party plugins to work without separately targeting Lab and Viewer

## Major tasks
 - [x] Implement Phosphor Application, using Sink as a template
 - [x] Implement JupyterFrontEnd for Viewer, adding in services and wiring up to Jupyter
 - [ ] Implement plugin loading for Viewer, adding IPyWidgets, Plotly, etc.
   - [x] Load Jupyter extensions into Viewer
   - [x] Load the common package mentioned above
   - Mostly follows from Sink
 - [x] Refactor DashboardViewer machinery as JupyterFrontEnd plugin
   - Add support for URLs
   - _Note that this will break old URLs_
   - Reuse machinery from Sink/Config server

## Risks

 - Potential gremlins re: CSS packaging, could show up implementing plugin loading
 - Could lose some time to build setup

## External Impacts

 - URLs will be different, compatible with kitchen sink past base URL
 - App will load faster
 - Excel export (and other commands?)  will work
 - All installed MIME type renderers etc will be supported (instead of seeing text or blank space)

## Staying the same or similar:

 - Viewer display of dashboard docs 
 - Viewer display of notebook docs (except maybe corner case of zero to show), i.e. equal horizontal weights for everything with showInViewer=true (the default for dashboard cells,  but toggle-able for all output cells) , min 300 pixel height with scroller if needed
 - Keeping kernel status banner (blue for uninitialized , orange executing cells, red kernel error, blue idle)

**Comment by YairMarcowMavenomics** [comment]
Joe's current guesstimate: 10-15 hours

**Comment by YairMarcowMavenomics** [comment]
A tiny but weird side issue this would hopefully fix automatically:  the animation slider part controls seem to render correctly in JupyterLab but not viewer.

E.g. looking at  ./view/demos/MBTA%20Realtime%20Statistics.ipynb  on Binder I see : 
 
![image](https://user-images.githubusercontent.com/2054227/68357087-39c45b00-00e2-11ea-9c68-ca5becaa7c57.png)

Feels like a missing/misdirected font-issue... maybe some CSS that wasn't included?

**Comment by quigleyj-mavenomics** [comment]
Probably. Those icons are FontAwesome 4.0 icons, so it's entirely possible that the stylesheets for that iconset just aren't included in the viewer (or are broken by something).

**Comment by quigleyj-mavenomics** [comment]
Another thought I just had is whether we can simply supplant the Viewer with Voila. I'm not familiar with Voila's internal workings, but presumably we can either supply plugins and a button for one-click-deployments (to replace the "Eyeball" button), or fork it to implement dashboard rendering. Might be worth investigating.

**Comment by quigleyj-mavenomics** [comment]
Whoops, didn't mean to close this. #66 addresses most, but not all concerns in this issue.

Specifically, we are still missing:

 - [ ] Support for IPyWidgets
 - [ ] Factorings/cleanup
 - [ ] URL overrides
