### ISSUE TITLE
Cleanup and organize MQL highlighting mode

### ISSUE THREAD

**Issue by quigleyj-mavenomics** [Mavenomics/MavenWorks#34]
Right now it's split across a few different files, including some code forked from CodeMirror. It's located in a weird package (`@mavenomics/default-parts`), and it's hard to work with and add onto since it doesn't slot into our extension framework very nicely.

**Comment by YairMarcowMavenomics** [comment]
This is purely technical debt, but already introduces drag, e.g. makes adding F11 go-to-definition difficult.

**Comment by quigleyj-mavenomics** [comment]
Looks like it wasn't auto-closed by the PR... guess I need to prepend "fixes" to _all_ issue refs I intend to close
