### ISSUE TITLE
include Descriptions in property hover help

### ISSUE THREAD

**Issue by YairMarcowMavenomics** [Mavenomics/MavenWorks#49]
Hover help show name, type and default, but not description (even for properties with narrative description in F1 help)

**Comment by quigleyj-mavenomics** [comment]
These _are_ actually shown in the tooltips: 
![image](https://user-images.githubusercontent.com/20070398/68441921-9e90bb80-019d-11ea-8278-ced5d3ddf2a3.png)

**Comment by YairMarcowMavenomics** [comment]
Looks like it's there for Layout but not Part Properties.

E.g. for AnimationSliderPart Enabled:

![image](https://user-images.githubusercontent.com/2054227/68444025-a6ebf500-01a3-11ea-8c37-196905830519.png)
